import Head from 'next/head'
import Footer from '../components/footer/index';
import Header from '../components/header/index';
import Main from "../components/main";
import Portfolio from "../components/portfolio";
import About from "../components/about";
import Contact from "../components/contact";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <Main/>
            <Portfolio/>
            <About/>
            <Contact/>
            <Footer/>
        </>
    )
}
